### PR TITLE
Fix upgrade v2

### PR DESCRIPTION
**Pull request by Josue-T**
## Problem

- Regressions since #27 
- stunnel is not more needed
- many config file not used

## Solution

- Fix regresssions
- Cleanup package
- Fix warnings

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by Josue-T** [comment]
!testme !bookwormtestme

**Comment by Josue-T** [comment]
!bookwormtestme

**Comment by cloo** [comment]
I'm getting "not allowed in state 1" when trying to send emails. Stunnel service is not there anymore, not sure how to debug..

**Comment by Josue-T** [comment]
Hello,

Well, stunnel was a workaround because SOGo didn't supported TLS for a long time. But now it support so some changes was made to not depends any more of stunnel.

Normally in `/var/log/sogo/sogo.log` you should have some log of your issue.

You can also check that the SOGo config have the correct IMAP/SMTP config by checking theses 2 lines:
```
  SOGoSMTPServer = "smtp://mydomain.tld:587/?tls=YES";
...
  SOGoIMAPServer = "imaps://mydomain.tld:993";
```

Some other check that you can do:
- Check that you have a valid certificate (not self signed) for mydomain.tld
- Check that this command return this following result:
```
# host mydomain.tld
mydomain.tld has address 127.0.0.1
mydomain.tld has IPv6 address ::1
```

**Pull request merged**
